### ISSUE TITLE
Security -> Cookie on / off switch doesn't persist

### ISSUE THREAD

**Issue by GaryJones** [riverside/http-headers#1]
![screenshot 2018-10-28 12 03 46](https://user-images.githubusercontent.com/88371/47615667-8aee4780-daa9-11e8-999d-99fe165a1669.png)

The radio option for the Security -> Cookie feature doesn't persist to On.

Version 1.10.4

Awesome plugin btw!

**Comment by riverside** [comment]
Seems to work on my end. Can you confirm the issue still exists on latest version?

**Comment by riverside** [comment]
Closed as not confirmed.
