### ISSUE TITLE
Add support for the NEL response header

### ISSUE THREAD

**Issue by ralish** [riverside/http-headers#5]
Great work on a fantastic plugin! Makes managing the ever-increasing number of important HTTP headers much easier.

One header the plugin doesn't currently support is the `NEL` (*Network Error Logging*) header. This header works in conjunction with the `Report-To` header to enable browsers to report network events such as failed requests. It's a relatively simple header, and given your existing support for `Report-To` I expect would be relatively simple to implement. What are your thoughts?

Some background information:
- [MDN: Network Error Logging](https://developer.mozilla.org/en-US/docs/Web/HTTP/Network_Error_Logging)
- [W3: Network Error Logging](https://www.w3.org/TR/network-error-logging/)
- [URIports: Why you need 'Network Error Logging' (NEL)](https://www.uriports.com/blog/network-error-logging/)

**Comment by riverside** [comment]
Sure, I will add it.

**Comment by riverside** [comment]
@ralish I've added the NEL header. See v1.16.0

**Comment by ralish** [comment]
Updated to latest release and `Report-To` header is now working as expected. Thanks again for the quick fix!
