### ISSUE TITLE
Configured Report-To response header is malformed

### ISSUE THREAD

**Issue by ralish** [riverside/http-headers#6]
The `Report-To` header returned by the plugin is not correctly formed.

A sample header as returned looks like the following (pretty for readability):
```json
{
    "url": "https://example.com/reports",
    "group": "default",
    "max-age": 86400
}
```

According to [Section 3.1](https://www.w3.org/TR/reporting/#header) of the specification the JSON object should have:
- An *optional* `group` (`string`) member
- An *optional* `include_subdomains` (`boolean`) member
- A *required* `max_age` (`number`; positive integer) member
- A *required* `endpoints` (`array`) member

The `url` member being returned is not expected at the top-level of the JSON object, but instead should be included as a required member of each array element in the `endpoints` member. Each array element may also include optional `priority` and `weight` members, but this is not supported yet by the plugin.

Taking the earlier returned response the correct format would be (pretty for readability):
```json
{
    "group": "default",
    "max_age": 86400,
    "endpoints": [
        {
            "url": "https://example.com/reports"
        }
    ]
}
```

The UI for configuring this header probably needs to be reworked a bit as it has the following related issues:
- A `group` contains one or more `endpoints` (as array elements). If multiple entries are provided with the same group, they should be added as separate array elements to the `endpoints` member of the same underlying `group`.
- The `include_subdomains` field is specific to a `group` and not a `url`. If two URLs are configured with the same group but different values for `include_subdomains`, this cannot be represented according to the specification.
- The same issue applies to `max_age`, which is specific to a `group` and not a `url`.

**Comment by riverside** [comment]
At the time of adding of Report-To response header, it follows the current specification. I guess it was changed over the time. I will check the spec and will fix the plugin.

Thanks for reporting the bug!

**Comment by ralish** [comment]
That'd make sense re: it having changed. I only noticed because the service we use for reporting was complaining about the header being invalid.

**Comment by riverside** [comment]
@ralish I've fixed the `Report-To` header. See v.1.16.0

**Comment by ralish** [comment]
Confirming have updated and the `NEL` header is working beautifully. Thanks for adding support so quickly!
