### ISSUE TITLE
Plugin Vulnerability

### ISSUE THREAD

**Issue by paragondigital** [riverside/http-headers#7]
Hello!

We've been alerted of a vulnerability involving SQL injection on the plugin regarding version 1.18.9

https://www.wordfence.com/threat-intel/vulnerabilities/wordpress-plugins/http-headers/http-headers-1189-authenticatedadministrator-sql-injection

A few users have reported this on the Plugin support:
https://wordpress.org/support/topic/vulnerability-65/
https://wordpress.org/support/topic/http-headers-1-18-9-authenticatedadministrator-sql-injection/

Thanks for your attention!

**Comment by riverside** [comment]
I’ve just released a new version (1.18.10) which address the issues.
