### ISSUE TITLE
HTTP Headers does not work for requests targeting a blog's rss feed

### ISSUE THREAD

**Issue by xeladu** [riverside/http-headers#8]
Hello,

I tried your plugin and it seems as it doesn't support altering requests that are sent to a WordPress blog's rss feed. 

The usual url is https://some-blog.com/feed. Here is my example feed -> https://quickcoder.org/feed

Although I activated the "Access-Control-Allow-Origin" header, it doesn't work for the feed page. I still get a CORS error when using a custom app to access the content. Other pages on my blog work fine though with this app.

If you need further information, I'd be happy to supply those. Thanks!

**Comment by riverside** [comment]
Hi @xeladu 

FYI: the access-control set of headers are being sent by the server only when the "Origin" request header is sent by the client/browser. However, I've just tested once again, and it works as expected. For reference please see the screenshots below.

![1](https://github.com/riverside/http-headers/assets/43607/3df21893-95e5-48e5-b674-caaf5e339d03)
![2](https://github.com/riverside/http-headers/assets/43607/ef486f08-80d8-4e8a-ac0b-1aeb5f321d6f)
![3](https://github.com/riverside/http-headers/assets/43607/05778f40-54bc-4dea-870f-230d04d7136b)
![4](https://github.com/riverside/http-headers/assets/43607/72a2b554-3526-48f2-96bf-fb34322b7ee8)

**Comment by xeladu** [comment]
Hello, 
I aligned all my settings with yours but I still wasn't lucky.

![image](https://github.com/riverside/http-headers/assets/97696030/e927c57c-8799-4b53-809d-afc0b44d9d69)

It works for any page (blog post, tag page, custom page, ...) on my blog, but not for the feed. And it doesn't make any difference if I have your plugin active or not.

So I seems like a different configuration issue not related to your plugin.

EDIT: My hoster BlueHost confirmed that my current hosting package does not include this capability. I don't know how they do it (they didn't want to explain), but if I upgrade to another (much more expensive) plan, it will work.

Thanks for the help!
