### ISSUE TITLE
credentialless option for Cross-Origin-Embedder-Policy header

### ISSUE THREAD

**Issue by taraskhvyl** [riverside/http-headers#9]
Hey!

Thanks a lot for this plugin!

There is a new experimental option `credentialless` for header `Cross-Origin-Embedder-Policy.` 
Ref: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Embedder-Policy

Is it possible to add? I can create a PR by myself if it's needed.

thanks in advance

**Comment by riverside** [comment]
Hi @taraskhvyl 

Yes, I will add this and alongside few other fixes. Thanks for suggesting it.

**Comment by taraskhvyl** [comment]
Thank you!

> Hi @taraskhvyl
> 
> Yes, I will add this and alongside few other fixes. Thanks for suggesting it.

**Comment by riverside** [comment]
It's done!
